<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="R90JDQN3" name="MESSAGES ADD TESTCASES" tests="5" failures="1" timestamp="22 Dec 2016 17:40:09 GMT" time="248.072" errors="0">
  <testcase name="create_a_new_message_without_clientname" time="49.431" classname="library.Messages_TestCases"/>
  <testcase name="create_a_new_message_without_a_message_name" time="63.345" classname="library.Messages_TestCases"/>
  <testcase name="create_a_new_message_without_brand" time="63.68" classname="library.Messages_TestCases">
    <failure type="java.lang.AssertionError" message="expected [6] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [1]
	at library.MessagesPage.validateUpdates(MessagesPage.java:229)
	at library.Messages_TestCases.create_a_new_message_without_brand(Messages_TestCases.java:88)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- create_a_new_message_without_brand -->
  <testcase name="click_cancel_message_button" time="28.271" classname="library.Messages_TestCases"/>
  <testcase name="delete_message_from_db" time="4.891" classname="library.Messages_TestCases"/>
</testsuite> <!-- MESSAGES ADD TESTCASES -->
